/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ratatouille.view;

import Controllers.receitaController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import ratatouille.model.entity.Receita;

/**
 *
 * @author carol
 */
public class TelaTabela extends javax.swing.JFrame {

    //preenchendo a tabela
    public TelaTabela() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        carregarTabela();
        
    }
    
    
    private void carregarTabela(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        receitaController controllerReceita = new receitaController();
        List<Receita> receitas = new ArrayList();
        
        receitas = controllerReceita.LerTodasReceitas();
        modelo.setRowCount(0);
        for (int i = 0;i<receitas.size();i++){
            modelo.addRow(receitas.get(i).obterDados());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonExcluirReceita = new java.awt.Button();
        buttonVoltar = new java.awt.Button();
        buttonLer = new java.awt.Button();
        buttonLer1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome da receita", "Autor", "Rendimento(porções)", "Categoria", "Tempo de preparo", "Ingredientes", "Passos", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("");

        buttonExcluirReceita.setBackground(new java.awt.Color(153, 153, 153));
        buttonExcluirReceita.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        buttonExcluirReceita.setLabel("Excluir receita");
        buttonExcluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirReceitaActionPerformed(evt);
            }
        });

        buttonVoltar.setBackground(new java.awt.Color(153, 153, 153));
        buttonVoltar.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        buttonVoltar.setLabel("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        buttonLer.setBackground(new java.awt.Color(153, 153, 153));
        buttonLer.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        buttonLer.setLabel("Ler receita");
        buttonLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLerActionPerformed(evt);
            }
        });

        buttonLer1.setBackground(new java.awt.Color(153, 153, 153));
        buttonLer1.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        buttonLer1.setLabel("Editar receita");
        buttonLer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(buttonExcluirReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(buttonLer1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(buttonLer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExcluirReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLer1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
       TelaInicio telaInicio = new TelaInicio();
       telaInicio.setVisible(true);
       dispose();
       
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonExcluirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirReceitaActionPerformed
        //excluindo receitas
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        receitaController controllerReceita = new receitaController(); 
        
        //serão apagadas todas as receitas que forem selecionadas
        
        int[] indices = jTable1.getSelectedRows();
       
        for (int i = 0;i < indices.length; i++){
            int id = Integer.valueOf(modelo.getValueAt(indices[i], 7).toString());
            controllerReceita.excluirReceita(id);
        }//TODO 
        
        carregarTabela();
    }//GEN-LAST:event_buttonExcluirReceitaActionPerformed

    private void buttonLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLerActionPerformed
        // Selecionando a receita        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        receitaController controllerReceita = new receitaController(); 
        Receita receita = new Receita();
   
        //pegando a primeira posicao do vetor, caso sejam selecionadas varias receitas
        int[] indices = jTable1.getSelectedRows();
       
        if (indices.length != 0){
            int id = Integer.valueOf(modelo.getValueAt(indices[0], 7).toString());
            receita = controllerReceita.LerReceita(id);
        
            TelaMostraReceita telaMostra = new TelaMostraReceita(receita);
            telaMostra.setVisible(true);
            dispose(); 
        }//TODO 
        
        
    }//GEN-LAST:event_buttonLerActionPerformed

    private void buttonLer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLer1ActionPerformed
        // Selecionando a receita
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        receitaController controllerReceita = new receitaController(); 
        Receita receita = new Receita();

        int[] indices = jTable1.getSelectedRows();
       
        if (indices.length != 0){
            int id = Integer.valueOf(modelo.getValueAt(indices[0], 7).toString());
            receita = controllerReceita.LerReceita(id);
        
            TelaEditaReceita telaEdita = new TelaEditaReceita(receita);
            telaEdita.setVisible(true);
            dispose(); 
        }
    }//GEN-LAST:event_buttonLer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonExcluirReceita;
    private java.awt.Button buttonLer;
    private java.awt.Button buttonLer1;
    private java.awt.Button buttonVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
