/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ratatouille.view;

import Controllers.receitaController;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javafx.scene.paint.Color;
import javax.swing.WindowConstants;
import ratatouille.model.entity.Receita;
import java.awt.Color;

/**
 *
 * @author carol
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNomeReceita = new javax.swing.JLabel();
        nomeDaReceita = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nomeDoAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rendimento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tempoDePreparo = new javax.swing.JTextField();
        buttonSalvar = new java.awt.Button();
        buttonVoltar = new java.awt.Button();
        categoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ingredientes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Passos = new javax.swing.JTextArea();
        validacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 236, 193));
        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(552, 640));

        jLabelNomeReceita.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabelNomeReceita.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomeReceita.setText("Nome da receita *");

        nomeDaReceita.setBackground(new java.awt.Color(255, 255, 255));
        nomeDaReceita.setForeground(new java.awt.Color(0, 0, 0));
        nomeDaReceita.setToolTipText("ex: \"Bolo de chocolate\"");
        nomeDaReceita.setCaretColor(new java.awt.Color(0, 0, 0));
        nomeDaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDaReceitaActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Autor ");

        nomeDoAutor.setBackground(new java.awt.Color(255, 255, 255));
        nomeDoAutor.setForeground(new java.awt.Color(0, 0, 0));
        nomeDoAutor.setToolTipText("ex: \"Mamãe\"");
        nomeDoAutor.setCaretColor(new java.awt.Color(0, 0, 0));
        nomeDoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoAutorActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Rendimento (porções) *");

        rendimento.setBackground(new java.awt.Color(255, 255, 255));
        rendimento.setForeground(new java.awt.Color(0, 0, 0));
        rendimento.setToolTipText("ex: \"1\"");
        rendimento.setCaretColor(new java.awt.Color(0, 0, 0));
        rendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendimentoActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Categoria * ");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Passos *");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tempo de preparo");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ingredientes *");

        tempoDePreparo.setBackground(new java.awt.Color(255, 255, 255));
        tempoDePreparo.setForeground(new java.awt.Color(0, 0, 0));
        tempoDePreparo.setToolTipText("ex: \"1.5\"");
        tempoDePreparo.setCaretColor(new java.awt.Color(0, 0, 0));
        tempoDePreparo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempoDePreparoActionPerformed(evt);
            }
        });

        buttonSalvar.setBackground(new java.awt.Color(102, 102, 102));
        buttonSalvar.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        buttonSalvar.setForeground(new java.awt.Color(0, 0, 0));
        buttonSalvar.setLabel("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonVoltar.setActionCommand("Voltar");
        buttonVoltar.setBackground(new java.awt.Color(102, 102, 102));
        buttonVoltar.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        buttonVoltar.setForeground(new java.awt.Color(0, 0, 0));
        buttonVoltar.setLabel("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        categoria.setBackground(new java.awt.Color(255, 255, 255));
        categoria.setForeground(new java.awt.Color(0, 0, 0));
        categoria.setToolTipText("ex: \"doce\"");
        categoria.setCaretColor(new java.awt.Color(0, 0, 0));
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });

        Ingredientes.setBackground(new java.awt.Color(255, 255, 255));
        Ingredientes.setColumns(20);
        Ingredientes.setForeground(new java.awt.Color(0, 0, 0));
        Ingredientes.setRows(5);
        Ingredientes.setToolTipText("\"ex: 1 xícara de chá de leite...\"");
        Ingredientes.setWrapStyleWord(true);
        Ingredientes.setBorder(null);
        Ingredientes.setCaretColor(new java.awt.Color(0, 0, 0));
        Ingredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ingredientes.setDoubleBuffered(true);
        Ingredientes.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jScrollPane1.setViewportView(Ingredientes);

        Passos.setBackground(new java.awt.Color(255, 255, 255));
        Passos.setColumns(20);
        Passos.setRows(5);
        Passos.setToolTipText("ex: \"Coloque os líquidos no liquidificador e bata até misturar bem...\"");
        Passos.setCaretColor(new java.awt.Color(0, 0, 0));
        Passos.setMargin(new java.awt.Insets(0, 1, 0, 0));
        jScrollPane2.setViewportView(Passos);

        validacao.setEditable(false);
        validacao.setBackground(new java.awt.Color(255, 236, 193));
        validacao.setForeground(new java.awt.Color(0, 204, 0));
        validacao.setToolTipText("");
        validacao.setBorder(null);
        validacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validacaoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 10)); // NOI18N
        jLabel2.setText("Somente números");

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 0, 10)); // NOI18N
        jLabel10.setText("Somente números");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempoDePreparo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeReceita)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(categoria)
                        .addComponent(rendimento)
                        .addComponent(nomeDoAutor)
                        .addComponent(nomeDaReceita)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(validacao, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194)
                        .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelNomeReceita)
                .addGap(8, 8, 8)
                .addComponent(nomeDaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeDoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempoDePreparo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(validacao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rato.png"))); // NOI18N
        jLabel1.setText("Cadastro de receitas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDaReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDaReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDaReceitaActionPerformed

    private void nomeDoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoAutorActionPerformed

    private void rendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rendimentoActionPerformed

    private void tempoDePreparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempoDePreparoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempoDePreparoActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed

        TelaInicio telaInicio = new TelaInicio();
        telaInicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private boolean validaCadastro() {

        if (nomeDaReceita.getText().isEmpty()) {
            return false;
        }
        if (rendimento.getText().isEmpty() || !rendimento.getText().matches("[0-9]+")) {
            return false;
        }
        if (Passos.getText().isEmpty()) {
            return false;
        }
        if (categoria.getText().isEmpty()) {
            return false;
        }
        if (Ingredientes.getText().isEmpty()) {
            return false;
        }
        if (!tempoDePreparo.getText().isEmpty() && !tempoDePreparo.getText().matches("[0-9]+")) {
            return false;
        }
        return true;
    }


    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        if (validaCadastro()) {

            Receita receita = new Receita();

            receita.setNomeDaReceita(nomeDaReceita.getText());
            receita.setNomeAutor(nomeDoAutor.getText());
            receita.setRendimentoPorcao(Integer.valueOf(rendimento.getText()));
            receita.setTempo(Float.valueOf(tempoDePreparo.getText()));
            receita.setCategoria(categoria.getText());
            receita.setPassos(Passos.getText());
            receita.setIngredientes(Ingredientes.getText());

            receitaController controllerReceita = new receitaController();
            controllerReceita.cadastrarReceita(receita);

            validacao.setText("Cadastrado com sucesso!");
            validacao.setForeground(Color.GREEN);
            nomeDaReceita.setText("");
            nomeDoAutor.setText("");
            rendimento.setText("");
            categoria.setText("");
            tempoDePreparo.setText("");
            Ingredientes.setText("");
            Passos.setText("");

        } else {
            validacao.setText("Erro ao cadastrar :(");
            validacao.setForeground(Color.RED);
        }

    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaActionPerformed

    private void validacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Ingredientes;
    private javax.swing.JTextArea Passos;
    private java.awt.Button buttonSalvar;
    private java.awt.Button buttonVoltar;
    private javax.swing.JTextField categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNomeReceita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeDaReceita;
    private javax.swing.JTextField nomeDoAutor;
    private javax.swing.JTextField rendimento;
    private javax.swing.JTextField tempoDePreparo;
    private javax.swing.JTextField validacao;
    // End of variables declaration//GEN-END:variables
}
